version: '3'
services:
  registry:
    restart: always
    build: .
    environment:
      - TZ=Asia/Tokyo
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
      - REGISTRY_PROXY_USERNAME=${REGISTRY_PROXY_USERNAME}
      - REGISTRY_PROXY_PASSWORD=${REGISTRY_PROXY_PASSWORD}
      - REGISTRY_STORAGE_S3_ACCESSKEY=${AWS_ACCESS_KEY_ID}
      - REGISTRY_STORAGE_S3_SECRETKEY=${AWS_SECRET_ACCESS_KEY}
      - REGISTRY_STORAGE_S3_REGION=ap-northeast-1
      - REGISTRY_STORAGE_S3_BUCKET=${S3_BUCKET_NAME}
    ports:
      - 3000:5000
  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
